# Generated by Django 4.1.3 on 2023-04-03 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='profile_pic',
        ),
    ]
