# Generated by Django 4.1.3 on 2023-04-03 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.teacher'),
        ),
    ]
