# Generated by Django 4.1.3 on 2023-04-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_add_driver_bus_name_alter_subjects_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='intimation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
    ]
