# Generated by Django 4.1.3 on 2023-04-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_adminhod_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transport_manager',
            options={'verbose_name': 'Transport', 'verbose_name_plural': 'Transports'},
        ),
        migrations.AddField(
            model_name='transport_manager',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
