# Generated by Django 4.1.3 on 2023-04-04 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_adminhod_options_remove_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[(1, 'HOD'), (2, 'STAFF'), (3, 'STUDENT'), (4, 'Transport Manager')], default=1, max_length=100),
        ),
    ]
