# Generated by Django 4.1.3 on 2023-04-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('hod', 'HOD'), ('staff', 'STAFF'), ('student', 'STUDENT'), ('transport_manager', 'Transport Manager')], max_length=100),
        ),
    ]
