# Generated by Django 4.1.3 on 2023-04-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_leave',
            name='date',
            field=models.DateField(max_length=100),
        ),
    ]
