# Generated by Django 4.1.3 on 2023-04-06 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_staff_leave_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_leave',
            name='staff_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.teacher'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.course'),
        ),
    ]
