# Generated by Django 4.1.3 on 2023-04-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_staff_leave_staff_id_alter_student_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('hod', 'HOD'), ('staff', 'STAFF'), ('student', 'STUDENT'), ('transport_manager', 'TRANSPORT_MANAGER')], max_length=100),
        ),
    ]
