# Generated by Django 4.1.3 on 2023-04-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminhod',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='adminhod',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
