# Generated by Django 4.1.3 on 2023-04-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_adminhod_address_adminhod_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('1', 'HOD'), ('2', 'Staff'), ('3', 'Student'), ('4', 'transport_manager')], max_length=10),
        ),
    ]
